apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jbx4w1mqq-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jbx4w1mqq-dotnet-basic-gitops